### ISSUE TITLE
Create Readme and contribution guide

### ISSUE THREAD

**Issue by manan-jadhav** [gdgbaroda/gdgbaroda.github.io#11]
Read me should tell more about what this repository is and how to use it.

Contributing guide should include guidelines to follow while contributing, such as file naming, image resizing, etc.

**Comment by dhruvapte26** [comment]
I will work on this 😄

**Comment by SnehPandya18** [comment]
@the-ethan-hunt I have created all contributing MDs (https://github.com/SnehPandya18/AndroidTemplate/community) for on of my Android repos which you can use for reference: https://github.com/SnehPandya18/AndroidTemplate

I collected the architecture, topics, notes, etc from Google Samples (https://github.com/googlesamples), Atom (https://github.com/atom) & many more repos to generate my contributing.

**Comment by dhruvapte26** [comment]
Questions for the maintainers, @CurosMJ and @SnehPandya18 :  
- Does the repo include a license? If yes, please tell me so I can add it in the `readme.md` and create a `LICENSE.md`
- More importantly, as specified by @CurosMJ what kind of **specific guidelines** to mention in the `CONTRIBUTING.md`? Would you please explain a little bit more in detail? Thanks in advance! 😄

**Comment by SnehPandya18** [comment]
@the-ethan-hunt 
* Sure it does. I would recommend Apache License 2.0 (https://choosealicense.com/licenses/apache-2.0/) & updating it as required for this particular repo (example: "Copyright [year] [name of the copyright owner]") (reference at the bottom: https://github.com/SnehPandya18/AndroidTemplate/blob/master/LICENSE.md)
* @CurosMJ can provide file naming conventions for the web. Images should be PNG or JPEG format (standard quality without any artistic effects or highlights) & also have a look how we are maintaining images in the same repo for markdown, wiki and everything in-between: https://github.com/gdgbaroda/books2go/wiki (edit the wiki to see the image-path & structure)

Hope this helps, more queries are welcomed!

**Comment by manan-jadhav** [comment]
Resolved, with 25b9228779b17f93aa7cda9cda4b71e45279b5bc
