### ISSUE TITLE
Blog post on "All about The Virtual Assistants"

### ISSUE THREAD

**Issue by HackyRoot** [gdgbaroda/gdgbaroda.github.io#32]
Writer: @harshpopat
He'll cover the following topics in his post
- What is a Virtual Assistant?
- How is it useful?
- What is it's practical examples?
- How does it work?
- Future of Virtual Assistants?

Any suggestions from the team?
CC: @CurosMJ , @SnehPandya18 @mistryhardik

**Comment by SnehPandya18** [comment]
@HackyRoot @harshpopat 
Good to go.

**Comment by DarshilBhatt** [comment]
Done #32
