### ISSUE TITLE
Blog post on Generative Adversarial Networks

### ISSUE THREAD

**Issue by dhruvapte26** [gdgbaroda/gdgbaroda.github.io#38]
Writer: @the-ethan-hunt
I would be covering the below mentioned topics in the post:
- A basic understanding of a GAN using a small example
- It's working in clear and concise language
- A brief 'touch' of the related math
- It's current uses in image recognition and other fields

Any suggestions from the maintainers: @SnehPandya18 @CurosMJ ?

**Comment by manan-jadhav** [comment]
Please follow contribution guidelines, use the proper description format.

**Comment by manan-jadhav** [comment]
Edit : My bad, I thought this was a PR.

**Comment by DarshilBhatt** [comment]
Done #38
