### ISSUE TITLE
Change post date to event date

### ISSUE THREAD

**Issue by manan-jadhav** [gdgbaroda/gdgbaroda.github.io#39]
I need someone to change the date of post to match the date when event actually happened. You will have to move the images to proper folders as well.

**Comment by SnehPandya18** [comment]
@HackyRoot this task is assigned to @knightkill

**Comment by SnehPandya18** [comment]
@knightkill can you please complete this on priority basis?

**Comment by knightkill** [comment]
Will do it by evening.

**Comment by knightkill** [comment]
Still I would suggest, it would be much better if @HackyRoot could do it. I have to yet to checkout Books2go thingy.

**Comment by DarshilBhatt** [comment]
Done #39
