### ISSUE TITLE
Blogpost on auto encoders 

### ISSUE THREAD

**Issue by dhruvapte26** [gdgbaroda/gdgbaroda.github.io#47]
The blogpost will be covering a simple autoencoder tutorial
- DL framework used- TensorFlow
- Dataset used- MNIST Handwritten-Digit Dataset
- Documentation: A Markdown post with code snippets from the original [Jupyter notebook](https://github.com/the-ethan-hunt/nervy-notebooks/blob/master/tensorflow/autoencoder_with_MNIST.ipynb)

Awaiting reviews from maintainers @SnehPandya18 and @CurosMJ

**Comment by knightkill** [comment]
Apologies @the-ethan-hunt, seems like everyone got quite busy.

Yes, the post seems helpful, and you could submit the post, but I would just currently close the issue as its been 4 years :)
