### ISSUE TITLE
Add contributors page and link in navbar

### ISSUE THREAD

**Issue by manan-jadhav** [gdgbaroda/gdgbaroda.github.io#53]

**Comment by passionInfinite** [comment]
@CurosMJ Need to add active members. Check PR #76

**Comment by HackyRoot** [comment]
@SnehPandya18 working on this one. Can you please send me a list of members you want to add.

**Comment by SnehPandya18** [comment]
Active members/contributors:
Hardip Patel
Kushal Dave
Hardik Mistry
Tanvi Shah
Chintan Shah
Aditya Patel
Dron Trivedi
Prachi Durge
Darshil Bhatt
Dhruv Apte
