### ISSUE TITLE
Duplicate IWD post

### ISSUE THREAD

**Issue by HackyRoot** [gdgbaroda/gdgbaroda.github.io#74]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Agdgbaroda
    
### Description

Duplicate IWD post

### Steps to Reproduce

1. Visit https://gdgbaroda.com/IWD/

**Expected behavior:** 
- URL should follow this URL structure https://gdgbaroda.com/events/POST_NAME
- All photos should have proper margin and padding 
- Metadata should contain all necesary details 

**Actual behavior:**
- Post is present in root directory https://gdgbaroda.com/IWD/ ; which should be in "event" directory
- The style guide is not followed, the page looks cluttered 

**Reproduces how often:** 100%

**Comment by passionInfinite** [comment]
@HackyRoot PR is opened :stuck_out_tongue_winking_eye:
