### ISSUE TITLE
Add upstream as remote

### ISSUE THREAD

**Issue by HackyRoot** [gdgbaroda/gdgbaroda.github.io#79]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Agdgbaroda
    
### Description

Can't add upstream master as a remote.

### Steps to Reproduce

1.cd gdgbaroda.github.io
2. git remote add upstream https://github.com/gdgbaroda.github.io
3.  git pull upstream master

**Expected behavior:** [What you expect to happen]
Fetch lastest changes from the upstram.

**Actual behavior:** [What actually happens]
remote: Not Found
fatal: repository 'https://github.com/gdgbaroda.github.io/' not found

**Reproduces how often:** [What percentage of the time does it reproduce?]
100

**Comment by manan-jadhav** [comment]
This is the URL you should be using, please follow githubs guide before
reporting. Thank you.

https://github.com/gdgbaroda/gdgbaroda.github.io.git

**Comment by SnehPandya18** [comment]
The issue is produced due to malformed URL and thus closing the reported issue.

**Comment by HackyRoot** [comment]
@CurosMJ I read that guide thus I created this issue to make a change in our contribution guide.
Should I submit a PR?

**Comment by SnehPandya18** [comment]
Sure, go ahead. This issue stays closed, we're expecting a separate PR with required fix.
